[package]
name = "semio-db-model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.52"
derive_more = "0.99.17"
semver = { version = "1.0.5", features = ["serde"] }
serde = { version = "1.0.136", features = ["derive"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
